### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by anliec** [jupe/puml2code#50]
Awesome work!
I wonder about the C++ support, from what I saw / reproduced from the example you give in the repo, the code generated for c++ is much less complete than the one of let say python. Some field and methods are missing, for example (no need of code quote here just look at [test/data](https://github.com/jupe/puml2code/tree/master/test/data)).

Not that big of a problem if I know what is supported and what is not, but I don't manage to understand why some appear and some don't...

Any pointer is welcome !

**Comment by jupe** [comment]
You are right, like I mention in README generators are not even close to perfect. Some languages are in better shape like you saw. C++ for example provide very basics, but should be correct from syntax point of view. There is templates for each language you could improve. If you provide simple example for puml and output you expected I could do it at some point. PR is always welcome 🙂

**Comment by jupe** [comment]
I guess #51 covera this issue.
