### ISSUE TITLE
Error when generating typescript code

### ISSUE THREAD

**Issue by quang-thinkiq** [jupe/puml2code#66]
Got this error, not sure what it is.

quang@quang uml % ~/Projects/puml2code/bin/puml2code -i classDiagram.puml -l typescript
Error: line: 1 column: 11: SyntaxError: Expected [ \t], [\n], or [\r\n] but "P" found.
    at PlantUmlToCode.generate (/Users/quang/Projects/puml2code/src/index.js:86:15)
quang@quang uml % ~/Projects/puml2code/bin/puml2code -i classDiagram.puml -l python    
Error: line: 1 column: 11: SyntaxError: Expected [ \t], [\n], or [\r\n] but "P" found.
    at PlantUmlToCode.generate (/Users/quang/Projects/puml2code/src/index.js:86:15)
quang@quang uml % ~/Projects/puml2code/bin/puml2code -i classDiagram.puml -l typescript
Error: line: 1 column: 11: SyntaxError: Expected [ \t], [\n], or [\r\n] but "P" found.
    at PlantUmlToCode.generate (/Users/quang/Projects/puml2code/src/index.js:86:15)

**Comment by jupe** [comment]
Could you provide minimal example which leads to this issue? probably some syntax you are using is not supported yet.

**Comment by quang-thinkiq** [comment]
Oh, I figured out, it was because I named the diagram at the first line (@startuml ProcessLayout). I used vs code to edit the file, it highlights the first line (@startuml), hover on it I see this message (Diagram unnamed. Try "@startuml name"). Removed it, and no longer had the issue above. Thank you.
